name: Salt Describe Python Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Build Python Packages (wheel and sdist)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Echo Version
        run: echo "${{ inputs.version }}"

      - name: Setup Version
        run: echo "${{ inputs.version }}" > version.txt

      - name: Build Wheel
        run: python -m build --outdir dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: salt-describe-${{ inputs.version }}-packages
          path: dist/*
          retention-days: 5

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}
